[font]
size = 12.0

[font.bold]
family = "monospace"
style = "Fire Code"

[font.bold_italic]
family = "monospace"
style = "Fira Code"

[font.italic]
family = "monospace"
style = "Fira Code"

[font.normal]
family = "monospace"
style = "Fira Code"
