[theme]
theme = "dracula"

[icons]
icons = "awesome6"

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "load"
format = " $icon 1min avg: $1m.eng(w:4) "
interval = 1

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "
format_alt = " $icon $frequency{ $boost|} "
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "temperature"
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "k10temp-pci-00c3"


[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 1

[[block]]
block = "backlight"
device = "amdgpu_bl1"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z', l:ru_RU) "
short = " $icon $timestamp.datetime(f:%R) "

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 15
