{ pkgs, ... }:

let
  myHelm = pkgs.wrapHelm pkgs.kubernetes-helm {
    plugins = with pkgs.kubernetes-helmPlugins; [
      helm-diff
      helm-secrets
      helm-s3
    ];
  };
  myHelmfile = pkgs.helmfile.override {
    inherit (myHelm.passthru) pluginsDir;
  };
in
{
  home.packages = with pkgs; [
    htop
    unzip
    zip
    (pkgs.python3.withPackages (python-pkgs: [
      python-pkgs.pandas
      python-pkgs.requests
      python-pkgs.click
      python-pkgs.pyyaml
      python-pkgs.jinja2
      python-pkgs.distlib
      python-pkgs.pykeepass
      ansible
    ]))
    nodejs
    clang
    zig
    gnumake
    git
    lua
    lazygit
    bat
    fzf
    ripgrep
    jq
    tree
    eza
    foot
    ghostty
    curl
    kitty
    screen
    tmux
    fd
    antigen
    docker
    zsh-autosuggestions
    pango
    fira-code
    nerd-fonts.fira-code
    pass
    passExtensions.pass-import
    xclip
    bc
    wl-clipboard
    xorg.xev
    xbindkeys
    xorg.xmodmap
    networkmanagerapplet
    maven
    telegram-desktop
    font-awesome
    jetbrains.idea
    acpi
    brightnessctl
    lshw
    pamixer
    brillo
    gparted
    parted
    bash
    feh
    swaybg
    swayidle
    swaylock-effects
    imagemagick
    openconnect
    networkmanager-openconnect
    networkmanager-vpnc
    spotify
    ansible
    go-task
    dig
    inetutils
    libreoffice
    cloc
    vscode
    zoom-us
    sshpass
    autorandr
    xlayoutdisplay
    oath-toolkit
    yamllint
    postgresql
    obsidian
    yq-go
    pnpm
    insomnia
    kubectl
    kustomize
    cointop
    quarkus
    qrencode
    httpie
    httpie-desktop
    bruno
    skopeo
    nmap
    kind
    sops
    age
    myHelm
    myHelmfile
    cargo
    aria2
    proxychains
    speedtest-cli
    nh
    p7zip
    xarchiver
    yandex-disk
    jira-cli-go
    opentofu
    terranix
    terragrunt
    tflint
    nixfmt-rfc-style
    npins
    treefmt
    jdt-language-server
    mergiraf
    nil
    floorp-bin
    ytt
    redocly
    clang-tools
    xorg.libX11
    xorg.libXi
    boost
    meson
    inkscape
    openapi-generator-cli
    gimp
    jmeter
    librechat
    allure
    aider-chat
    aichat
    opencode
    ollama-rocm
    google-chrome
    jbang
    flameshot
    peek
    grim
    slurp
    fuzzel
    cliphist
    swaynotificationcenter
    libnotify
    appimage-run
    python312Packages.psycopg2
    woeusb-ng
    k9s
    deluge
    python312Packages.click
    dbeaver-bin
    vhs
    hurl
    clojure
    ncdu
    dust
    hwatch
    mktoc
    mkdocs
    soapui
    keepassxc
    nextcloud-client
  ];
}
